import 'listening_question.dart';

const Map<String, List<ListeningQuestion>> listeningContents = {
  // ============================================================
  // ENGLISH
  // ============================================================

  'en_b1': [
    ListeningQuestion(
      id: 'en_b1_l001',
      lessonId: 'en_b1',
      audioText: 'I usually go to work by train.',
      question: 'How does the speaker usually go to work?',
      options: ['By car', 'By bus', 'By train', 'By bicycle'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b1_l002',
      lessonId: 'en_b1',
      audioText: 'She is meeting her friend at seven o’clock.',
      question: 'When is she meeting her friend?',
      options: ['At five', 'At six', 'At seven', 'At eight'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b1_l003',
      lessonId: 'en_b1',
      audioText: 'Tom bought a new jacket because the weather was cold.',
      question: 'Why did Tom buy a new jacket?',
      options: [
        'It was raining.',
        'The weather was cold.',
        'His old jacket was lost.',
        'He needed a gift.'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b1_l004',
      lessonId: 'en_b1',
      audioText: 'We are going to the cinema after dinner.',
      question: 'Where are they going after dinner?',
      options: ['To the park', 'To the cinema', 'To a restaurant', 'To school'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b1_l005',
      lessonId: 'en_b1',
      audioText: 'Maria drinks coffee every morning before work.',
      question: 'When does Maria drink coffee?',
      options: [
        'After work',
        'At lunchtime',
        'Every morning',
        'Before bed'
      ],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b1_l006',
      lessonId: 'en_b1',
      audioText: 'The supermarket closes at nine tonight.',
      question: 'When does the supermarket close?',
      options: ['At seven', 'At eight', 'At nine', 'At ten'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b1_l007',
      lessonId: 'en_b1',
      audioText: 'John forgot his umbrella, so he got wet.',
      question: 'Why did John get wet?',
      options: [
        'He forgot his umbrella.',
        'He lost his coat.',
        'He missed the bus.',
        'He stayed outside all night.'
      ],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'en_b1_l008',
      lessonId: 'en_b1',
      audioText: 'My sister is studying medicine at university.',
      question: 'What is the speaker’s sister studying?',
      options: ['Law', 'Medicine', 'History', 'Art'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b1_l009',
      lessonId: 'en_b1',
      audioText: 'They played football in the park yesterday afternoon.',
      question: 'Where did they play football?',
      options: ['At school', 'At home', 'In the park', 'At the beach'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b1_l010',
      lessonId: 'en_b1',
      audioText: 'I need to buy some bread and milk on my way home.',
      question: 'What does the speaker need to buy?',
      options: [
        'Bread and milk',
        'Fruit and juice',
        'Cheese and eggs',
        'Rice and vegetables'
      ],
      correctIndex: 0,
    ),
  ],

  'en_b2': [
    ListeningQuestion(
      id: 'en_b2_l001',
      lessonId: 'en_b2',
      audioText: 'The meeting was postponed because the manager was ill.',
      question: 'Why was the meeting postponed?',
      options: [
        'The room was unavailable.',
        'The manager was ill.',
        'The employees were late.',
        'The weather was bad.'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b2_l002',
      lessonId: 'en_b2',
      audioText: 'Although the hotel was expensive, we decided to stay there.',
      question: 'Why did they stay at the hotel?',
      options: [
        'It was cheap.',
        'It was close to the airport.',
        'They decided to stay despite the price.',
        'A friend recommended another hotel.'
      ],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b2_l003',
      lessonId: 'en_b2',
      audioText: 'The train arrived twenty minutes later than expected.',
      question: 'How late was the train?',
      options: ['Ten minutes', 'Fifteen minutes', 'Twenty minutes', 'Thirty minutes'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b2_l004',
      lessonId: 'en_b2',
      audioText: 'She decided to work from home because the office was being renovated.',
      question: 'Why did she work from home?',
      options: [
        'She was feeling tired.',
        'The office was being renovated.',
        'She had a meeting online.',
        'She wanted to travel.'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b2_l005',
      lessonId: 'en_b2',
      audioText: 'The course is designed for people who already have basic computer skills.',
      question: 'Who is the course designed for?',
      options: [
        'Complete beginners',
        'Children',
        'People with basic computer skills',
        'Professional programmers'
      ],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b2_l006',
      lessonId: 'en_b2',
      audioText: 'We could have taken the bus, but walking was actually faster.',
      question: 'Why did they walk?',
      options: [
        'The bus was expensive.',
        'Walking was faster.',
        'There was no bus.',
        'They wanted exercise.'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b2_l007',
      lessonId: 'en_b2',
      audioText: 'The restaurant received excellent reviews after changing its menu.',
      question: 'What happened after the menu changed?',
      options: [
        'The restaurant closed.',
        'Prices increased.',
        'It received excellent reviews.',
        'Fewer people visited.'
      ],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b2_l008',
      lessonId: 'en_b2',
      audioText: 'He would have joined us if he had finished work earlier.',
      question: 'Why did he not join them?',
      options: [
        'He was travelling.',
        'He finished work late.',
        'He was sick.',
        'He forgot the meeting.'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b2_l009',
      lessonId: 'en_b2',
      audioText: 'The company plans to introduce flexible working hours next year.',
      question: 'What does the company plan to introduce?',
      options: [
        'A new office',
        'Flexible working hours',
        'Shorter holidays',
        'A new salary system'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b2_l010',
      lessonId: 'en_b2',
      audioText: 'Despite the heavy traffic, we arrived before the presentation began.',
      question: 'When did they arrive?',
      options: [
        'After the presentation',
        'During the presentation',
        'Before the presentation',
        'The next morning'
      ],
      correctIndex: 2,
    ),
  ],

  'en_b3': [
    ListeningQuestion(
      id: 'en_b3_l001',
      lessonId: 'en_b3',
      audioText: 'The research suggests that regular breaks can improve concentration.',
      question: 'What can regular breaks improve?',
      options: ['Memory loss', 'Concentration', 'Sleep', 'Physical strength'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b3_l002',
      lessonId: 'en_b3',
      audioText: 'The speaker argues that technology should support teachers rather than replace them.',
      question: 'What is the speaker’s main argument?',
      options: [
        'Technology should replace teachers.',
        'Teachers should avoid technology.',
        'Technology should support teachers.',
        'Technology is unnecessary.'
      ],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b3_l003',
      lessonId: 'en_b3',
      audioText: 'The project was delayed partly because several team members changed departments.',
      question: 'What contributed to the delay?',
      options: [
        'A lack of funding',
        'Team members changing departments',
        'Bad weather',
        'A technical failure'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b3_l004',
      lessonId: 'en_b3',
      audioText: 'The report emphasizes the importance of long-term planning.',
      question: 'What does the report emphasize?',
      options: [
        'Short-term profits',
        'Long-term planning',
        'Staff reductions',
        'International travel'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b3_l005',
      lessonId: 'en_b3',
      audioText: 'The speaker was initially skeptical, but the results eventually convinced her.',
      question: 'How did the speaker’s opinion change?',
      options: [
        'She became more skeptical.',
        'She remained uncertain.',
        'She was eventually convinced.',
        'She rejected the results.'
      ],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_b3_l006',
      lessonId: 'en_b3',
      audioText: 'The museum has expanded its digital collection to make research materials more accessible.',
      question: 'Why did the museum expand its digital collection?',
      options: [
        'To reduce staff',
        'To make materials more accessible',
        'To close the museum',
        'To increase ticket prices'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b3_l007',
      lessonId: 'en_b3',
      audioText: 'The policy was introduced in response to growing concerns about data privacy.',
      question: 'Why was the policy introduced?',
      options: [
        'Because of data privacy concerns',
        'Because of higher profits',
        'Because employees requested holidays',
        'Because the office moved'
      ],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'en_b3_l008',
      lessonId: 'en_b3',
      audioText: 'The speaker acknowledges the benefits of the proposal but questions its practical cost.',
      question: 'What concern does the speaker raise?',
      options: [
        'Its popularity',
        'Its practical cost',
        'Its historical importance',
        'Its environmental effect'
      ],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_b3_l009',
      lessonId: 'en_b3',
      audioText: 'The findings challenge the assumption that working longer always leads to better results.',
      question: 'What assumption do the findings challenge?',
      options: [
        'Longer work always produces better results.',
        'Shorter meetings are better.',
        'Employees need training.',
        'Technology saves time.'
      ],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'en_b3_l010',
      lessonId: 'en_b3',
      audioText: 'The lecture concludes that successful communication depends on both clarity and active listening.',
      question: 'What does successful communication depend on?',
      options: [
        'Speed and confidence',
        'Technology and grammar',
        'Clarity and active listening',
        'Writing and reading'
      ],
      correctIndex: 2,
    ),
  ],

  'en_a5': [
    ListeningQuestion(
      id: 'en_a5_l001',
      lessonId: 'en_a5',
      audioText: 'I am looking for the train station.',
      question: 'What is the speaker looking for?',
      options: ['The airport', 'The train station', 'The hotel', 'The bank'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_a5_l002',
      lessonId: 'en_a5',
      audioText: 'My favorite color is blue.',
      question: 'What is the speaker’s favorite color?',
      options: ['Red', 'Green', 'Blue', 'Yellow'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_a5_l003',
      lessonId: 'en_a5',
      audioText: 'There are three books on the table.',
      question: 'How many books are on the table?',
      options: ['One', 'Two', 'Three', 'Four'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_a5_l004',
      lessonId: 'en_a5',
      audioText: 'She has a small dog.',
      question: 'What animal does she have?',
      options: ['A cat', 'A dog', 'A bird', 'A rabbit'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_a5_l005',
      lessonId: 'en_a5',
      audioText: 'The coffee is very hot.',
      question: 'How is the coffee?',
      options: ['Cold', 'Sweet', 'Hot', 'Bitter'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'en_a5_l006',
      lessonId: 'en_a5',
      audioText: 'We live in a big city.',
      question: 'Where do they live?',
      options: ['In a village', 'In a big city', 'On a farm', 'Near a lake'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_a5_l007',
      lessonId: 'en_a5',
      audioText: 'He is wearing a black jacket.',
      question: 'What is he wearing?',
      options: ['A white shirt', 'A black jacket', 'Blue trousers', 'A red coat'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_a5_l008',
      lessonId: 'en_a5',
      audioText: 'I have breakfast at eight o’clock.',
      question: 'When does the speaker have breakfast?',
      options: ['At seven', 'At eight', 'At nine', 'At ten'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_a5_l009',
      lessonId: 'en_a5',
      audioText: 'The children are playing outside.',
      question: 'Where are the children playing?',
      options: ['Inside', 'Outside', 'At school', 'In the car'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'en_a5_l010',
      lessonId: 'en_a5',
      audioText: 'Please open the window.',
      question: 'What does the speaker ask someone to do?',
      options: ['Close the door', 'Open the window', 'Turn off the light', 'Sit down'],
      correctIndex: 1,
    ),
  ],

  // ============================================================
  // ITALIAN
  // ============================================================

  'it_b1': [
    ListeningQuestion(
      id: 'it_b1_l001',
      lessonId: 'it_b1',
      audioText: 'Di solito vado al lavoro in treno.',
      question: 'Come va di solito al lavoro?',
      options: ['In macchina', 'In autobus', 'In treno', 'In bicicletta'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b1_l002',
      lessonId: 'it_b1',
      audioText: 'Lei incontra la sua amica alle sette.',
      question: 'Quando incontra la sua amica?',
      options: ['Alle cinque', 'Alle sei', 'Alle sette', 'Alle otto'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b1_l003',
      lessonId: 'it_b1',
      audioText: 'Marco compra una giacca perché fa freddo.',
      question: 'Perché Marco compra una giacca?',
      options: ['Perché piove.', 'Perché fa freddo.', 'Perché è estate.', 'Perché è un regalo.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b1_l004',
      lessonId: 'it_b1',
      audioText: 'Dopo cena andiamo al cinema.',
      question: 'Dove vanno dopo cena?',
      options: ['Al parco', 'Al cinema', 'A scuola', 'In ufficio'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b1_l005',
      lessonId: 'it_b1',
      audioText: 'Maria beve il caffè ogni mattina prima del lavoro.',
      question: 'Quando beve il caffè Maria?',
      options: ['Ogni mattina', 'Ogni sera', 'A pranzo', 'Dopo il lavoro'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'it_b1_l006',
      lessonId: 'it_b1',
      audioText: 'Il supermercato chiude alle nove questa sera.',
      question: 'A che ora chiude il supermercato?',
      options: ['Alle sette', 'Alle otto', 'Alle nove', 'Alle dieci'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b1_l007',
      lessonId: 'it_b1',
      audioText: 'Giovanni ha dimenticato l’ombrello ed è arrivato bagnato.',
      question: 'Perché Giovanni è arrivato bagnato?',
      options: ['Ha dimenticato l’ombrello.', 'Ha perso il cappotto.', 'Ha preso il treno.', 'Era in ritardo.'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'it_b1_l008',
      lessonId: 'it_b1',
      audioText: 'Mia sorella studia medicina all’università.',
      question: 'Che cosa studia sua sorella?',
      options: ['Legge', 'Medicina', 'Storia', 'Arte'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b1_l009',
      lessonId: 'it_b1',
      audioText: 'Ieri pomeriggio hanno giocato a calcio al parco.',
      question: 'Dove hanno giocato a calcio?',
      options: ['A scuola', 'A casa', 'Al parco', 'In spiaggia'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b1_l010',
      lessonId: 'it_b1',
      audioText: 'Devo comprare pane e latte tornando a casa.',
      question: 'Che cosa deve comprare?',
      options: ['Pane e latte', 'Frutta e succo', 'Formaggio e uova', 'Riso e verdure'],
      correctIndex: 0,
    ),
  ],

  'it_b2': [
    ListeningQuestion(
      id: 'it_b2_l001',
      lessonId: 'it_b2',
      audioText: 'La riunione è stata rimandata perché il direttore era malato.',
      question: 'Perché è stata rimandata la riunione?',
      options: ['La sala era occupata.', 'Il direttore era malato.', 'I dipendenti erano in ritardo.', 'Pioveva.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b2_l002',
      lessonId: 'it_b2',
      audioText: 'Anche se l’albergo era costoso, abbiamo deciso di restare.',
      question: 'Perché hanno deciso di restare?',
      options: ['Era economico.', 'Era vuoto.', 'Hanno deciso di restare nonostante il prezzo.', 'Era vicino a casa.'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b2_l003',
      lessonId: 'it_b2',
      audioText: 'Il treno è arrivato venti minuti più tardi del previsto.',
      question: 'Quanto era in ritardo il treno?',
      options: ['Dieci minuti', 'Quindici minuti', 'Venti minuti', 'Trenta minuti'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b2_l004',
      lessonId: 'it_b2',
      audioText: 'Ha deciso di lavorare da casa perché l’ufficio era in ristrutturazione.',
      question: 'Perché ha lavorato da casa?',
      options: ['Era stanca.', 'L’ufficio era in ristrutturazione.', 'Era in vacanza.', 'Aveva un appuntamento.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b2_l005',
      lessonId: 'it_b2',
      audioText: 'Il corso è pensato per persone che hanno già conoscenze informatiche di base.',
      question: 'Per chi è pensato il corso?',
      options: ['Per principianti assoluti', 'Per bambini', 'Per persone con conoscenze informatiche di base', 'Per programmatori professionisti'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b2_l006',
      lessonId: 'it_b2',
      audioText: 'Avremmo potuto prendere l’autobus, ma andare a piedi era più veloce.',
      question: 'Perché sono andati a piedi?',
      options: ['Era più economico.', 'Era più veloce.', 'Non c’era autobus.', 'Volevano fare sport.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b2_l007',
      lessonId: 'it_b2',
      audioText: 'Il ristorante ha ricevuto ottime recensioni dopo aver cambiato il menu.',
      question: 'Che cosa è successo dopo il cambiamento del menu?',
      options: ['Ha chiuso.', 'Ha aumentato i prezzi.', 'Ha ricevuto ottime recensioni.', 'Ha perso clienti.'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b2_l008',
      lessonId: 'it_b2',
      audioText: 'Sarebbe venuto con noi se avesse finito il lavoro prima.',
      question: 'Perché non è venuto?',
      options: ['Era in viaggio.', 'Ha finito il lavoro tardi.', 'Era malato.', 'Ha dimenticato l’appuntamento.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b2_l009',
      lessonId: 'it_b2',
      audioText: 'L’azienda prevede di introdurre orari di lavoro flessibili l’anno prossimo.',
      question: 'Che cosa prevede di introdurre l’azienda?',
      options: ['Un nuovo ufficio', 'Orari di lavoro flessibili', 'Meno ferie', 'Un nuovo stipendio'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b2_l010',
      lessonId: 'it_b2',
      audioText: 'Nonostante il traffico intenso, siamo arrivati prima dell’inizio della presentazione.',
      question: 'Quando sono arrivati?',
      options: ['Dopo la presentazione', 'Durante la presentazione', 'Prima della presentazione', 'Il giorno dopo'],
      correctIndex: 2,
    ),
  ],

  'it_b3': [
    ListeningQuestion(
      id: 'it_b3_l001',
      lessonId: 'it_b3',
      audioText: 'La ricerca suggerisce che pause regolari possono migliorare la concentrazione.',
      question: 'Che cosa possono migliorare le pause regolari?',
      options: ['La memoria', 'La concentrazione', 'La forza fisica', 'Il sonno'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b3_l002',
      lessonId: 'it_b3',
      audioText: 'Secondo il relatore, la tecnologia dovrebbe aiutare gli insegnanti invece di sostituirli.',
      question: 'Qual è l’idea principale del relatore?',
      options: ['La tecnologia deve sostituire gli insegnanti.', 'La tecnologia deve aiutare gli insegnanti.', 'Gli insegnanti non devono usare la tecnologia.', 'La tecnologia non serve.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b3_l003',
      lessonId: 'it_b3',
      audioText: 'Il progetto è stato ritardato anche perché alcuni membri del gruppo hanno cambiato reparto.',
      question: 'Che cosa ha contribuito al ritardo?',
      options: ['Il maltempo', 'Il cambio di reparto di alcuni membri', 'La mancanza di computer', 'Un viaggio'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b3_l004',
      lessonId: 'it_b3',
      audioText: 'Il rapporto sottolinea l’importanza della pianificazione a lungo termine.',
      question: 'Che cosa sottolinea il rapporto?',
      options: ['I profitti immediati', 'La pianificazione a lungo termine', 'Le vacanze', 'La pubblicità'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b3_l005',
      lessonId: 'it_b3',
      audioText: 'All’inizio era scettica, ma alla fine i risultati l’hanno convinta.',
      question: 'Come è cambiata la sua opinione?',
      options: ['È diventata più scettica.', 'È rimasta incerta.', 'Alla fine è stata convinta.', 'Ha rifiutato i risultati.'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_b3_l006',
      lessonId: 'it_b3',
      audioText: 'Il museo ha ampliato la sua collezione digitale per rendere i materiali più accessibili.',
      question: 'Perché il museo ha ampliato la collezione digitale?',
      options: ['Per ridurre il personale', 'Per rendere i materiali più accessibili', 'Per chiudere il museo', 'Per aumentare i prezzi'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b3_l007',
      lessonId: 'it_b3',
      audioText: 'La politica è stata introdotta in risposta alle crescenti preoccupazioni sulla privacy dei dati.',
      question: 'Perché è stata introdotta la politica?',
      options: ['Per le preoccupazioni sulla privacy dei dati', 'Per aumentare i profitti', 'Per ridurre le ferie', 'Per trasferire l’ufficio'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'it_b3_l008',
      lessonId: 'it_b3',
      audioText: 'Il relatore riconosce i vantaggi della proposta, ma mette in dubbio il suo costo pratico.',
      question: 'Quale problema solleva il relatore?',
      options: ['La popolarità', 'Il costo pratico', 'La storia', 'La pubblicità'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_b3_l009',
      lessonId: 'it_b3',
      audioText: 'I risultati mettono in discussione l’idea che lavorare più a lungo porti sempre a risultati migliori.',
      question: 'Quale idea mettono in discussione i risultati?',
      options: ['Lavorare più a lungo porta sempre risultati migliori.', 'Le pause sono inutili.', 'La tecnologia è importante.', 'Il lavoro di gruppo è necessario.'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'it_b3_l010',
      lessonId: 'it_b3',
      audioText: 'La lezione conclude che una comunicazione efficace dipende dalla chiarezza e dall’ascolto attivo.',
      question: 'Da cosa dipende una comunicazione efficace?',
      options: ['Dalla velocità', 'Dalla tecnologia', 'Dalla chiarezza e dall’ascolto attivo', 'Dalla scrittura'],
      correctIndex: 2,
    ),
  ],

  'it_a5': [
    ListeningQuestion(
      id: 'it_a5_l001',
      lessonId: 'it_a5',
      audioText: 'Cerco la stazione ferroviaria.',
      question: 'Che cosa cerca il parlante?',
      options: ['L’aeroporto', 'La stazione ferroviaria', 'L’hotel', 'La banca'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_a5_l002',
      lessonId: 'it_a5',
      audioText: 'Il mio colore preferito è il blu.',
      question: 'Qual è il suo colore preferito?',
      options: ['Rosso', 'Verde', 'Blu', 'Giallo'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_a5_l003',
      lessonId: 'it_a5',
      audioText: 'Ci sono tre libri sul tavolo.',
      question: 'Quanti libri ci sono sul tavolo?',
      options: ['Uno', 'Due', 'Tre', 'Quattro'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_a5_l004',
      lessonId: 'it_a5',
      audioText: 'Lei ha un cane piccolo.',
      question: 'Quale animale ha?',
      options: ['Un gatto', 'Un cane', 'Un uccello', 'Un coniglio'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_a5_l005',
      lessonId: 'it_a5',
      audioText: 'Il caffè è molto caldo.',
      question: 'Com’è il caffè?',
      options: ['Freddo', 'Dolce', 'Caldo', 'Amaro'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'it_a5_l006',
      lessonId: 'it_a5',
      audioText: 'Viviamo in una grande città.',
      question: 'Dove vivono?',
      options: ['In un villaggio', 'In una grande città', 'In una fattoria', 'Vicino a un lago'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_a5_l007',
      lessonId: 'it_a5',
      audioText: 'Lui indossa una giacca nera.',
      question: 'Che cosa indossa?',
      options: ['Una camicia bianca', 'Una giacca nera', 'Pantaloni blu', 'Un cappotto rosso'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_a5_l008',
      lessonId: 'it_a5',
      audioText: 'Faccio colazione alle otto.',
      question: 'A che ora fa colazione?',
      options: ['Alle sette', 'Alle otto', 'Alle nove', 'Alle dieci'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_a5_l009',
      lessonId: 'it_a5',
      audioText: 'I bambini stanno giocando fuori.',
      question: 'Dove stanno giocando i bambini?',
      options: ['Dentro', 'Fuori', 'A scuola', 'In macchina'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'it_a5_l010',
      lessonId: 'it_a5',
      audioText: 'Per favore, apri la finestra.',
      question: 'Che cosa chiede di fare?',
      options: ['Chiudere la porta', 'Aprire la finestra', 'Spegnere la luce', 'Sedersi'],
      correctIndex: 1,
    ),
  ],

  // ============================================================
  // ARABIC
  // ============================================================

  'ar_b1': [
    ListeningQuestion(
      id: 'ar_b1_l001',
      lessonId: 'ar_b1',
      audioText: 'عادةً أذهب إلى العمل بالقطار.',
      question: 'كيف يذهب عادةً إلى العمل؟',
      options: ['بالسيارة', 'بالحافلة', 'بالقطار', 'بالدراجة'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b1_l002',
      lessonId: 'ar_b1',
      audioText: 'هي تقابل صديقتها في الساعة السابعة.',
      question: 'متى تقابل صديقتها؟',
      options: ['الساعة الخامسة', 'الساعة السادسة', 'الساعة السابعة', 'الساعة الثامنة'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b1_l003',
      lessonId: 'ar_b1',
      audioText: 'اشترى سامي سترة جديدة لأن الجو كان بارداً.',
      question: 'لماذا اشترى سامي سترة جديدة؟',
      options: ['لأن الجو كان ممطراً.', 'لأن الجو كان بارداً.', 'لأنها كانت هدية.', 'لأنه فقد حقيبته.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b1_l004',
      lessonId: 'ar_b1',
      audioText: 'سنذهب إلى السينما بعد العشاء.',
      question: 'إلى أين سيذهبون بعد العشاء؟',
      options: ['إلى الحديقة', 'إلى السينما', 'إلى المدرسة', 'إلى المكتب'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b1_l005',
      lessonId: 'ar_b1',
      audioText: 'تشرب ماريا القهوة كل صباح قبل العمل.',
      question: 'متى تشرب ماريا القهوة؟',
      options: ['كل صباح', 'كل مساء', 'وقت الغداء', 'بعد العمل'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'ar_b1_l006',
      lessonId: 'ar_b1',
      audioText: 'يغلق المتجر في الساعة التاسعة الليلة.',
      question: 'متى يغلق المتجر؟',
      options: ['في السابعة', 'في الثامنة', 'في التاسعة', 'في العاشرة'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b1_l007',
      lessonId: 'ar_b1',
      audioText: 'نسي أحمد مظلته، ولذلك ابتل بالمطر.',
      question: 'لماذا ابتل أحمد؟',
      options: ['لأنه نسي مظلته.', 'لأنه فقد معطفه.', 'لأنه تأخر.', 'لأنه ذهب إلى البحر.'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'ar_b1_l008',
      lessonId: 'ar_b1',
      audioText: 'أختي تدرس الطب في الجامعة.',
      question: 'ماذا تدرس أخته؟',
      options: ['القانون', 'الطب', 'التاريخ', 'الفن'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b1_l009',
      lessonId: 'ar_b1',
      audioText: 'لعبوا كرة القدم في الحديقة أمس بعد الظهر.',
      question: 'أين لعبوا كرة القدم؟',
      options: ['في المدرسة', 'في المنزل', 'في الحديقة', 'على الشاطئ'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b1_l010',
      lessonId: 'ar_b1',
      audioText: 'أحتاج إلى شراء الخبز والحليب في طريقي إلى المنزل.',
      question: 'ماذا يحتاج إلى شراء؟',
      options: ['الخبز والحليب', 'الفاكهة والعصير', 'الجبن والبيض', 'الأرز والخضروات'],
      correctIndex: 0,
    ),
  ],

  'ar_b2': [
    ListeningQuestion(
      id: 'ar_b2_l001',
      lessonId: 'ar_b2',
      audioText: 'تم تأجيل الاجتماع لأن المدير كان مريضاً.',
      question: 'لماذا تم تأجيل الاجتماع؟',
      options: ['لأن الغرفة كانت مشغولة.', 'لأن المدير كان مريضاً.', 'لأن الموظفين تأخروا.', 'لأن الطقس كان سيئاً.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b2_l002',
      lessonId: 'ar_b2',
      audioText: 'رغم أن الفندق كان غالياً، قررنا البقاء فيه.',
      question: 'لماذا قرروا البقاء في الفندق؟',
      options: ['لأنه رخيص.', 'لأنه فارغ.', 'قرروا البقاء رغم السعر.', 'لأنه قريب من المنزل.'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b2_l003',
      lessonId: 'ar_b2',
      audioText: 'وصل القطار بعد عشرين دقيقة من الموعد المتوقع.',
      question: 'كم دقيقة تأخر القطار؟',
      options: ['عشر دقائق', 'خمس عشرة دقيقة', 'عشرون دقيقة', 'ثلاثون دقيقة'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b2_l004',
      lessonId: 'ar_b2',
      audioText: 'قررت العمل من المنزل لأن المكتب كان قيد التجديد.',
      question: 'لماذا عملت من المنزل؟',
      options: ['لأنها كانت متعبة.', 'لأن المكتب كان قيد التجديد.', 'لأنها كانت في عطلة.', 'لأن لديها موعداً.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b2_l005',
      lessonId: 'ar_b2',
      audioText: 'الدورة مصممة للأشخاص الذين لديهم مهارات أساسية في الحاسوب.',
      question: 'لمن صممت الدورة؟',
      options: ['للمبتدئين تماماً', 'للأطفال', 'للأشخاص الذين لديهم مهارات أساسية في الحاسوب', 'للمبرمجين المحترفين'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b2_l006',
      lessonId: 'ar_b2',
      audioText: 'كان بإمكاننا ركوب الحافلة، لكن المشي كان أسرع.',
      question: 'لماذا مشوا؟',
      options: ['لأنه كان أرخص.', 'لأنه كان أسرع.', 'لم تكن هناك حافلة.', 'لأنهم أرادوا ممارسة الرياضة.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b2_l007',
      lessonId: 'ar_b2',
      audioText: 'حصل المطعم على تقييمات ممتازة بعد تغيير قائمته.',
      question: 'ماذا حدث بعد تغيير القائمة؟',
      options: ['أغلق المطعم.', 'رفع الأسعار.', 'حصل على تقييمات ممتازة.', 'خسر الزبائن.'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b2_l008',
      lessonId: 'ar_b2',
      audioText: 'لكان قد انضم إلينا لو أنه أنهى العمل مبكراً.',
      question: 'لماذا لم ينضم إليهم؟',
      options: ['كان مسافراً.', 'أنهى العمل متأخراً.', 'كان مريضاً.', 'نسي الموعد.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b2_l009',
      lessonId: 'ar_b2',
      audioText: 'تخطط الشركة لتقديم ساعات عمل مرنة في العام المقبل.',
      question: 'ماذا تخطط الشركة لتقديمه؟',
      options: ['مكتباً جديداً', 'ساعات عمل مرنة', 'إجازات أقل', 'نظام رواتب جديد'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b2_l010',
      lessonId: 'ar_b2',
      audioText: 'رغم الازدحام الشديد، وصلنا قبل بدء العرض.',
      question: 'متى وصلوا؟',
      options: ['بعد العرض', 'أثناء العرض', 'قبل العرض', 'في اليوم التالي'],
      correctIndex: 2,
    ),
  ],

  'ar_b3': [
    ListeningQuestion(
      id: 'ar_b3_l001',
      lessonId: 'ar_b3',
      audioText: 'تشير الدراسة إلى أن الاستراحات المنتظمة يمكن أن تحسن التركيز.',
      question: 'ماذا يمكن أن تحسن الاستراحات المنتظمة؟',
      options: ['الذاكرة', 'التركيز', 'القوة البدنية', 'النوم'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b3_l002',
      lessonId: 'ar_b3',
      audioText: 'يرى المتحدث أن التكنولوجيا يجب أن تدعم المعلمين بدلاً من أن تحل محلهم.',
      question: 'ما الفكرة الرئيسية للمتحدث؟',
      options: ['يجب أن تحل التكنولوجيا محل المعلمين.', 'يجب أن تدعم التكنولوجيا المعلمين.', 'يجب تجنب التكنولوجيا.', 'التكنولوجيا غير ضرورية.'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b3_l003',
      lessonId: 'ar_b3',
      audioText: 'تأخر المشروع جزئياً لأن بعض أعضاء الفريق انتقلوا إلى أقسام أخرى.',
      question: 'ما الذي ساهم في التأخير؟',
      options: ['الطقس السيئ', 'انتقال بعض أعضاء الفريق إلى أقسام أخرى', 'نقص التمويل', 'السفر'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b3_l004',
      lessonId: 'ar_b3',
      audioText: 'يؤكد التقرير أهمية التخطيط على المدى الطويل.',
      question: 'ماذا يؤكد التقرير؟',
      options: ['الأرباح السريعة', 'التخطيط على المدى الطويل', 'الإجازات', 'الإعلانات'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b3_l005',
      lessonId: 'ar_b3',
      audioText: 'كانت في البداية متشككة، لكن النتائج أقنعتها في النهاية.',
      question: 'كيف تغير رأيها؟',
      options: ['أصبحت أكثر تشككاً.', 'بقيت غير متأكدة.', 'اقتَنعت في النهاية.', 'رفضت النتائج.'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_b3_l006',
      lessonId: 'ar_b3',
      audioText: 'وسع المتحف مجموعته الرقمية لجعل المواد البحثية أكثر سهولة في الوصول إليها.',
      question: 'لماذا وسع المتحف مجموعته الرقمية؟',
      options: ['لتقليل عدد الموظفين', 'لجعل المواد أكثر سهولة في الوصول إليها', 'لإغلاق المتحف', 'لرفع الأسعار'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b3_l007',
      lessonId: 'ar_b3',
      audioText: 'تم تقديم السياسة استجابة للمخاوف المتزايدة بشأن خصوصية البيانات.',
      question: 'لماذا تم تقديم السياسة؟',
      options: ['بسبب مخاوف خصوصية البيانات', 'بسبب زيادة الأرباح', 'بسبب تقليل الإجازات', 'بسبب نقل المكتب'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'ar_b3_l008',
      lessonId: 'ar_b3',
      audioText: 'يعترف المتحدث بفوائد الاقتراح لكنه يشكك في تكلفته العملية.',
      question: 'ما المشكلة التي يثيرها المتحدث؟',
      options: ['شعبيته', 'تكلفته العملية', 'أهميته التاريخية', 'تأثيره الإعلاني'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_b3_l009',
      lessonId: 'ar_b3',
      audioText: 'تتحدى النتائج الافتراض بأن العمل لساعات أطول يؤدي دائماً إلى نتائج أفضل.',
      question: 'ما الافتراض الذي تتحداه النتائج؟',
      options: ['العمل لساعات أطول يؤدي دائماً إلى نتائج أفضل.', 'الاستراحات غير مفيدة.', 'التكنولوجيا مهمة.', 'العمل الجماعي ضروري.'],
      correctIndex: 0,
    ),
    ListeningQuestion(
      id: 'ar_b3_l010',
      lessonId: 'ar_b3',
      audioText: 'تخلص المحاضرة إلى أن التواصل الناجح يعتمد على الوضوح والاستماع الفعال.',
      question: 'على ماذا يعتمد التواصل الناجح؟',
      options: ['السرعة والثقة', 'التكنولوجيا والقواعد', 'الوضوح والاستماع الفعال', 'الكتابة والقراءة'],
      correctIndex: 2,
    ),
  ],

  'ar_a5': [
    ListeningQuestion(
      id: 'ar_a5_l001',
      lessonId: 'ar_a5',
      audioText: 'أبحث عن محطة القطار.',
      question: 'ماذا يبحث المتحدث؟',
      options: ['المطار', 'محطة القطار', 'الفندق', 'البنك'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_a5_l002',
      lessonId: 'ar_a5',
      audioText: 'لوني المفضل هو الأزرق.',
      question: 'ما اللون المفضل؟',
      options: ['الأحمر', 'الأخضر', 'الأزرق', 'الأصفر'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_a5_l003',
      lessonId: 'ar_a5',
      audioText: 'هناك ثلاثة كتب على الطاولة.',
      question: 'كم كتاباً على الطاولة؟',
      options: ['كتاب واحد', 'كتابان', 'ثلاثة كتب', 'أربعة كتب'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_a5_l004',
      lessonId: 'ar_a5',
      audioText: 'لديها كلب صغير.',
      question: 'ما الحيوان الذي لديها؟',
      options: ['قطة', 'كلب', 'طائر', 'أرنب'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_a5_l005',
      lessonId: 'ar_a5',
      audioText: 'القهوة ساخنة جداً.',
      question: 'كيف هي القهوة؟',
      options: ['باردة', 'حلوة', 'ساخنة', 'مرة'],
      correctIndex: 2,
    ),
    ListeningQuestion(
      id: 'ar_a5_l006',
      lessonId: 'ar_a5',
      audioText: 'نعيش في مدينة كبيرة.',
      question: 'أين يعيشون؟',
      options: ['في قرية', 'في مدينة كبيرة', 'في مزرعة', 'قرب بحيرة'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_a5_l007',
      lessonId: 'ar_a5',
      audioText: 'هو يرتدي سترة سوداء.',
      question: 'ماذا يرتدي؟',
      options: ['قميصاً أبيض', 'سترة سوداء', 'بنطالاً أزرق', 'معطفاً أحمر'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_a5_l008',
      lessonId: 'ar_a5',
      audioText: 'أتناول الفطور في الساعة الثامنة.',
      question: 'متى يتناول الفطور؟',
      options: ['في السابعة', 'في الثامنة', 'في التاسعة', 'في العاشرة'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_a5_l009',
      lessonId: 'ar_a5',
      audioText: 'الأطفال يلعبون في الخارج.',
      question: 'أين يلعب الأطفال؟',
      options: ['في الداخل', 'في الخارج', 'في المدرسة', 'في السيارة'],
      correctIndex: 1,
    ),
    ListeningQuestion(
      id: 'ar_a5_l010',
      lessonId: 'ar_a5',
      audioText: 'من فضلك افتح النافذة.',
      question: 'ماذا يطلب المتحدث؟',
      options: ['إغلاق الباب', 'فتح النافذة', 'إطفاء الضوء', 'الجلوس'],
      correctIndex: 1,
    ),
  ],
};

