// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1TCuUILUR5rdQYTEg8jDgY3xbOu74zso',
    appId: '1:1018988849924:web:7ea7df2e6c3aef7908be51',
    messagingSenderId: '1018988849924',
    projectId: 'arab-it-2f334',
    authDomain: 'arab-it-2f334.firebaseapp.com',
    storageBucket: 'arab-it-2f334.firebasestorage.app',
    measurementId: 'G-4S8S7NP8WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnVME40FxbI28rK0pwT2BGYjuaq02XWdM',
    appId: '1:1018988849924:android:2cb4da78ff5c4cc308be51',
    messagingSenderId: '1018988849924',
    projectId: 'arab-it-2f334',
    storageBucket: 'arab-it-2f334.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtCmwQ2nDUrPjgw57iQZyAjefIq8lGqw',
    appId: '1:1018988849924:ios:9b9fd3bc15928e9d08be51',
    messagingSenderId: '1018988849924',
    projectId: 'arab-it-2f334',
    storageBucket: 'arab-it-2f334.firebasestorage.app',
    iosClientId: '1018988849924-c2m7ht382m1fvmr7apqg9h8ic1o5mkk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.languageAcademy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEtCmwQ2nDUrPjgw57iQZyAjefIq8lGqw',
    appId: '1:1018988849924:ios:9b9fd3bc15928e9d08be51',
    messagingSenderId: '1018988849924',
    projectId: 'arab-it-2f334',
    storageBucket: 'arab-it-2f334.firebasestorage.app',
    iosClientId: '1018988849924-c2m7ht382m1fvmr7apqg9h8ic1o5mkk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.languageAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1TCuUILUR5rdQYTEg8jDgY3xbOu74zso',
    appId: '1:1018988849924:web:56dbc5371914790308be51',
    messagingSenderId: '1018988849924',
    projectId: 'arab-it-2f334',
    authDomain: 'arab-it-2f334.firebaseapp.com',
    storageBucket: 'arab-it-2f334.firebasestorage.app',
    measurementId: 'G-494H6KHXTY',
  );
}

